version: '3.6'

services:
  bitcoin:
    restart: on-failure
    image: realnuts/docker_pivx:4.1.1
    ports:
      - "51472:51472"
      - "51473:51473"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/pivx_data:/home/pivx
    command:
       - "-printtoconsole"
       - "-regtest=0"
       - "-rest"
       - "-rpcallowip=172.0.0.0/8"
       - "-rpcallowip=10.10.50.0/24"
       - "-rpcallowip=127.0.0.1/0"
       - "-rpcuser=foo"
       - "-rpcpassword=test"
       - "-wallet=wallet1"
       - "-txindex"
       - "-rpcport=51472"
       - "-rpcbind=0.0.0.0:51472"
       - "-server"
